# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [11]:
import numpy as np
import random

#### 2. Print your NumPy version.

In [12]:
print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [24]:
a = np.random.randint(0, 100, size=(2, 3,5))

array([[[64, 93, 40, 13, 37],
        [51, 76, 92, 94, 21],
        [22, 43, 16, 80,  7]],

       [[34,  3, 41, 69,  0],
        [49, 61, 92, 45, 74],
        [86, 10, 82, 84, 55]]])

In [26]:
a.dtype

dtype('int64')

In [ ]:
# Method 3

#### 4. Print *a*.


In [27]:
a

array([[[64, 93, 40, 13, 37],
        [51, 76, 92, 94, 21],
        [22, 43, 16, 80,  7]],

       [[34,  3, 41, 69,  0],
        [49, 61, 92, 45, 74],
        [86, 10, 82, 84, 55]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [74]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [76]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [81]:
print(np.array_equal(a,b))


False


In [82]:
print(np.allclose(a,b))


False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [83]:
a = np.random.randint(0, 100, size=(2, 3,5))
b = np.ones((5,2,3))
c = np.concatenate((a, b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [100]:
c=b.T
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [134]:
d = np.concatenate((a,c))
d

array([[[27., 27., 65., 49., 50.],
        [71., 47., 55., 70., 11.],
        [94.,  0., 13., 91., 43.]],

       [[36., 50.,  9., 20., 82.],
        [97., 28., 41., 72., 51.],
        [89., 21., 44., 93., 95.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [111]:
a

array([[[92, 36, 65, 22, 58],
        [17, 26, 28, 50, 98],
        [79, 56, 54, 73, 19]],

       [[31,  5, 38, 56, 56],
        [ 4, 36, 37, 22, 89],
        [19,  0, 14,  2, 64]]])

In [113]:
d

array([[[92., 36., 65., 22., 58.],
        [17., 26., 28., 50., 98.],
        [79., 56., 54., 73., 19.]],

       [[31.,  5., 38., 56., 56.],
        [ 4., 36., 37., 22., 89.],
        [19.,  0., 14.,  2., 64.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [116]:
e= a*c
e

array([[[92., 36., 65., 22., 58.],
        [17., 26., 28., 50., 98.],
        [79., 56., 54., 73., 19.]],

       [[31.,  5., 38., 56., 56.],
        [ 4., 36., 37., 22., 89.],
        [19.,  0., 14.,  2., 64.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [120]:
if e.all == a.all:
    print('True')
else:
    print('False')

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [125]:
d_min = np.min(d)
d_min

0.0

In [126]:
d_max = np.max(d)
d_max

98.0

In [128]:
d_mean = np.mean(d)
d_mean

21.266666666666666

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [131]:
f=np.empty((2,3,5))
f

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [170]:
f = []
for x in np.nditer(d):
    if d_min<x<d_mean:
        f += [25]
    elif d_mean<x<d_max:
        f += [75]
    elif x == d_mean:
        f += [50]
    elif x == d_min:
        f += [0]
    elif x == d_max:
        f =+ [100]
f=np.reshape(f,d.shape)
print(f)

[[[75 75 75 75 75]
  [75 75 75 75 25]
  [75  0 25 75 75]]

 [[75 75 25 25 75]
  [75 75 75 75 75]
  [75 25 75 75 75]]

 [[25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]]

 [[25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [171]:
print(d)

[[[27. 27. 65. 49. 50.]
  [71. 47. 55. 70. 11.]
  [94.  0. 13. 91. 43.]]

 [[36. 50.  9. 20. 82.]
  [97. 28. 41. 72. 51.]
  [89. 21. 44. 93. 95.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]]


In [172]:
print(f)

[[[75 75 75 75 75]
  [75 75 75 75 25]
  [75  0 25 75 75]]

 [[75 75 25 25 75]
  [75 75 75 75 75]
  [75 25 75 75 75]]

 [[25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]]

 [[25 25 25 25 25]
  [25 25 25 25 25]
  [25 25 25 25 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [173]:
f = []
for x in np.nditer(d):
    if d_min<x<d_mean:
        f += ['B']
    elif d_mean<x<d_max:
        f += ['D']
    elif x == d_mean:
        f += ['C']
    elif x == d_min:
        f += ['A']
    elif x == d_max:
        f =+ ['E']
f=np.reshape(f,d.shape)
print(f)

[[['D' 'D' 'D' 'D' 'D']
  ['D' 'D' 'D' 'D' 'B']
  ['D' 'A' 'B' 'D' 'D']]

 [['D' 'D' 'B' 'B' 'D']
  ['D' 'D' 'D' 'D' 'D']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']]

 [['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']]]
